name: Build And Publish Docker Image

on: 
   push: 
    tags: 
      - '*'
    
jobs:
    build_and_push_docker_image_to_docker_hub:
        name: Build and Push Docker Image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.1

            - name: Log-In to Docker Hub
              uses: docker/login-action@v3.0.0
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
                logout: true
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3.1.0
              with:
                cleanup: true
            
            - name: Get Release Tag Number
              id: release_tag_number
              uses: dawidd6/action-get-tag@v1.1.0
              with:
                strip_v: true
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v5.1.0
              with:
                no-cache: true
                push: true
                context: ${{github.workspace}}/
                target: serveprod
                tags: ${{secrets.DOCKER_USERNAME}}/task-manager-rest-api:${{steps.release_tag_number.outputs.tag}}
            